apiVersion: v1
kind: Service
metadata:
  name: gagan
  namespace: gitops
spec:
  type: LoadBalancer
  selector:
    app: django  #like tag
  ports:
    - protocol: TCP
      port: 80    #host port
      targetPort: 8000
      # nodePort: 31033